#!/bin/bash

# Set path etc.
source ~/.zshenv

# Run local .xenv
source ~/.xenv

# xset for bitmap font
xset +fp ~/.fonts
xset fp rehash

# Configure X environment
xrdb ~/.Xresources
echo 'Xft.dpi:' $PPI | xrdb -merge
urxvtd -f -o

compton --dbus &
xsetroot -cursor_name left_ptr &
xset +fp /usr/share/fonts/local/,/home/mro95/.fonts/ &
wp &
panel &
kb &
dunst &
vpsnotifyc &
urxvtd -f -o &
pulseaudio &
sxhkd &
wmname LG3D &
redshift &


bspc config border_width       $(ppi 3)
#bspc config window_gap         $(ppi 15)
bspc config window_gap         0
bspc config top_padding        $(ppi 25)

bspc config focused_border_color '#4d4f51'
bspc config active_border_color  '#242628'
bspc config normal_border_color  '#242628'
bspc config urgent_border_color  '#ffaf00'
bspc config presel_border_color  '#5a5c5e'

bspc config split_ratio               0.50
bspc config auto_cancel               true
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config focus_by_distance         true
bspc config focus_follows_pointer     false
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors  true
bspc config initial_polarity          second_child
bspc config pointer_modifier          mod4
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner
bspc config click_to_focus            true

bspc rule -a mplayer  state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a mpv      state=floating
bspc rule -a feh      state=floating
bspc rule -a Oblogout state=floating
bspc rule -a jetbrains-phpstorm desktop=^1

# Define more rules in ~/.xenv - for example:
# > bspc config -d 1-2 window_gap 0
# > bspc rule -a chromium desktop=1-2 border=off

# Define monitors in ~/.xenv - for example:
# > export monitors=( 'HDMI-0' 'DVI-D-0' 'DVI-I-1' )
# Note: Order is important!
# Desktops will be named 1-1, 1-2, ..., 1-6, 2-1, 2-2, ..., n-m where n means monitor and m means desktop

i=1
for m in "${monitors[@]}"; do
    if [[ "$(bspc wm -d | json 'return this.monitors.some(monitor => monitor.name == "'"$m"'");')" = 'true' ]]; then
        bspc monitor "$m" -d $i-{1..9}
        let i++
    fi
done

# Define autostart applications in ~/.xenv - for example:
# > function bspwm-autostart() {
# >     chromium &
# >     steam &
# > }

bspwm-autostart
